from  Vector3DClass import Vec3d
A = Vec3d(6, 8, 12)
B = Vec3d(10, 16, 12)
print("A is", A)
print("B is", B)
print("Magnitude of A is", A.get_length())
print("A+B is", A+B)
print("A-B is", A-B)
print("A normalized is", A.normalized())
print("A*2 is", A * 2)